### ISSUE TITLE
Problem in recyclerview header on Xiaomi and Huawei devices.

### ISSUE THREAD

**Issue by FawziQeshta** [Codewaves/Sticky-Header-Grid#33]
This problem happened when I use header recycler on Xiaomi and Huawei devices.

Fatal Exception: java.lang.NullPointerException
Attempt to read from field 'android.view.View androidx.recyclerview.widget.RecyclerView$d0.itemView' on a null object reference

Stack trace: Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'android.view.View androidx.recyclerview.widget.RecyclerView$d0.itemView' on a null object reference
       at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:2)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:49)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:1)
       at com.codewaves.stickyheadergrid.StickyHeaderGridLayoutManager.onLayoutChildren(StickyHeaderGridLayoutManager.java:31)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:38)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:37)
       at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:2)
       at android.view.View.layout(View.java:20710)
       at android.view.ViewGroup.layout(ViewGroup.java:6198)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
       at android.view.View.layout(View.java:20710)
       at android.view.ViewGroup.layout(ViewGroup.java:6198)
       at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:258)
       at android.view.View.layout(View.java:20710)
       at android.view.ViewGroup.layout(ViewGroup.java:6198)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
       at android.view.View.layout(View.java:20710)
       at android.view.ViewGroup.layout(ViewGroup.java:6198)
       at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:56)
       at android.view.View.layout(View.java:20710)
       at android.view.ViewGroup.layout(ViewGroup.java:6198)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:20710)
       at android.view.ViewGroup.layout(ViewGroup.java:6198)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
       at android.view.View.layout(View.java:20710)
       at android.view.ViewGroup.layout(ViewGroup.java:6198)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:20710)
       at android.view.ViewGroup.layout(ViewGroup.java:6198)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
       at android.view.View.layout(View.java:20710)
       at android.view.ViewGroup.layout(ViewGroup.java:6198)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:757)
       at android.view.View.layout(View.java:20710)
       at android.view.ViewGroup.layout(ViewGroup.java:6198)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2871)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2398)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1534)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7420)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1100)
       at android.view.Choreographer.doCallbacks(Choreographer.java:895)
       at android.view.Choreographer.doFrame(Choreographer.java:826)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1086)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6861)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by FawziQeshta** [comment]
Up
